import { db, Opportunity } from 'astro:db';

const OPORTUNIDADES = [
  // Ingeniería Informática
  {
    id: 'opp_inf_001',
    titulo: 'Desarrollador Web Frontend',
    empresa: 'TechStart Solutions',
    tipo: 'micro-pasantia',
    horasSemanales: 15,
    duracionSemanas: 8,
    duracionLabel: '8 semanas',
    ubicacion: 'San Salvador',
    descripcion:
      'Apoyo en React y TypeScript para producto SaaS. Mentoría semanal y código en producción.',
    requisitos: JSON.stringify(['React', 'JavaScript', 'Git']),
    carreras: JSON.stringify(['Licenciatura en Ciencias de la Computación', 'Técnico en Desarrollo de Aplicaciones Informáticas']),
  },
  {
    id: 'opp_inf_002',
    titulo: 'Asistente de Base de Datos',
    empresa: 'DataFlow Corp',
    tipo: 'pasantia',
    horasSemanales: 20,
    duracionSemanas: 12,
    duracionLabel: '12 semanas',
    ubicacion: 'Santa Tecla',
    descripcion: 'Diseño SQL, optimización de consultas y documentación para el equipo de datos.',
    requisitos: JSON.stringify(['SQL', 'Python', 'Modelado de datos']),
    carreras: JSON.stringify(['Licenciatura en Ciencias de la Computación', 'Técnico en Desarrollo de Aplicaciones Informáticas']),
  },
  {
    id: 'opp_inf_003',
    titulo: 'Proyecto: App móvil campus',
    empresa: 'Lab Innovación ULS',
    tipo: 'proyecto',
    horasSemanales: 10,
    duracionSemanas: 6,
    duracionLabel: '6 semanas',
    ubicacion: 'Campus ULS',
    descripcion: 'Prototipo Flutter/React Native para servicios estudiantiles con entrega de MVP.',
    requisitos: JSON.stringify(['Mobile', 'UI/UX', 'Trabajo en equipo']),
    carreras: JSON.stringify(['Licenciatura en Ciencias de la Computación', 'Técnico en Desarrollo de Aplicaciones Informáticas']),
  },
  {
    id: 'opp_inf_004',
    titulo: 'DevOps Junior',
    empresa: 'CloudNine SV',
    tipo: 'pasantia',
    horasSemanales: 18,
    duracionSemanas: 10,
    duracionLabel: '10 semanas',
    ubicacion: 'Remoto',
    descripcion: 'CI/CD, contenedores Docker y despliegues en entorno de staging.',
    requisitos: JSON.stringify(['Linux', 'Docker', 'Git']),
    carreras: JSON.stringify(['Licenciatura en Ciencias de la Computación', 'Técnico en Desarrollo de Aplicaciones Informáticas']),
  },
  // Agroecología
  {
    id: 'opp_civ_001',
    titulo: 'Técnico de Campo Agroecológico',
    empresa: 'Cooperativa Agrícola El Porvenir',
    tipo: 'pasantia',
    horasSemanales: 20,
    duracionSemanas: 12,
    duracionLabel: '12 semanas',
    ubicacion: 'La Libertad',
    descripcion: 'Monitoreo de cultivos, gestión de compost y bitácoras técnicas bajo supervisión.',
    requisitos: JSON.stringify(['Agronomía básica', 'Trabajo de campo', 'Informes técnicos']),
    carreras: JSON.stringify(['Ingeniería Agroecológica', 'Técnico en Ingeniería Agroecológica']),
  },
  {
    id: 'opp_civ_002',
    titulo: 'Auxiliar en Gestión de Suelos',
    empresa: 'MAG — Ministerio de Agricultura',
    tipo: 'micro-pasantia',
    horasSemanales: 12,
    duracionSemanas: 8,
    duracionLabel: '8 semanas',
    ubicacion: 'San Salvador',
    descripcion: 'Análisis de muestras de suelo, cartografía y registro de datos para proyectos.',
    requisitos: JSON.stringify(['Edafología', 'Manejo de datos', 'Excel']),
    carreras: JSON.stringify(['Ingeniería Agroecológica', 'Técnico en Ingeniería Agroecológica']),
  },
  {
    id: 'opp_civ_003',
    titulo: 'Proyecto: Agricultura orgánica comunitaria',
    empresa: 'Municipalidad — convenio ULS',
    tipo: 'proyecto',
    horasSemanales: 8,
    duracionSemanas: 5,
    duracionLabel: '5 semanas',
    ubicacion: 'Campus ULS',
    descripcion: 'Implementación de huerto orgánico escolar con comunidad local.',
    requisitos: JSON.stringify(['Permacultura', 'Trabajo comunitario']),
    carreras: JSON.stringify(['Ingeniería Agroecológica', 'Técnico en Ingeniería Agroecológica']),
  },
  {
    id: 'opp_civ_004',
    titulo: 'Inspector de Calidad Agrícola',
    empresa: 'Grupo Agroexport SV',
    tipo: 'empleo',
    horasSemanales: 40,
    duracionSemanas: 26,
    duracionLabel: '6 meses',
    ubicacion: 'San Salvador',
    descripcion: 'Control de calidad en procesos poscosecha y cadena de exportación.',
    requisitos: JSON.stringify(['Normas de inocuidad', 'Comunicación']),
    carreras: JSON.stringify(['Ingeniería Agroecológica']),
  },
  // Administración
  {
    id: 'opp_adm_001',
    titulo: 'Asistente Marketing Digital',
    empresa: 'Digital Marketing Pro',
    tipo: 'micro-pasantia',
    horasSemanales: 12,
    duracionSemanas: 6,
    duracionLabel: '6 semanas',
    ubicacion: 'Remoto',
    descripcion: 'Contenido para redes, métricas y campañas email para PYMEs.',
    requisitos: JSON.stringify(['Redes sociales', 'Canva', 'Redacción']),
    carreras: JSON.stringify(['Licenciatura en Administración de Empresas']),
  },
  {
    id: 'opp_adm_002',
    titulo: 'Analista de Operaciones',
    empresa: 'Logística Centroamérica',
    tipo: 'pasantia',
    horasSemanales: 16,
    duracionSemanas: 10,
    duracionLabel: '10 semanas',
    ubicacion: 'San Salvador',
    descripcion: 'KPIs de inventario, reportes en Excel y mejora de procesos.',
    requisitos: JSON.stringify(['Excel', 'Análisis de datos', 'Comunicación']),
    carreras: JSON.stringify(['Licenciatura en Administración de Empresas']),
  },
  {
    id: 'opp_adm_003',
    titulo: 'Proyecto: Plan de negocios social',
    empresa: 'Incubadora ULS Emprende',
    tipo: 'proyecto',
    horasSemanales: 8,
    duracionSemanas: 4,
    duracionLabel: '4 semanas',
    ubicacion: 'Campus ULS',
    descripcion: 'Elaboración de plan financiero y pitch para startup estudiantil.',
    requisitos: JSON.stringify(['Finanzas básicas', 'Presentaciones']),
    carreras: JSON.stringify(['Licenciatura en Administración de Empresas']),
  },
  {
    id: 'opp_adm_004',
    titulo: 'Asistente de Recursos Humanos',
    empresa: 'PeopleFirst SV',
    tipo: 'pasantia',
    horasSemanales: 15,
    duracionSemanas: 12,
    duracionLabel: '12 semanas',
    ubicacion: 'Santa Tecla',
    descripcion: 'Reclutamiento, entrevistas y onboarding de personal.',
    requisitos: JSON.stringify(['Comunicación', 'Office', 'Ética profesional']),
    carreras: JSON.stringify(['Licenciatura en Administración de Empresas']),
  },
  // Contaduría Pública
  {
    id: 'opp_con_001',
    titulo: 'Practicante de Contabilidad',
    empresa: 'Contadores Asociados',
    tipo: 'pasantia',
    horasSemanales: 16,
    duracionSemanas: 10,
    duracionLabel: '10 semanas',
    ubicacion: 'San Salvador',
    descripcion: 'Registro de operaciones, conciliaciones y apoyo en cierre mensual.',
    requisitos: JSON.stringify(['Excel', 'Contabilidad básica']),
    carreras: JSON.stringify(['Licenciatura en Contaduría Pública']),
  },
  {
    id: 'opp_con_002',
    titulo: 'Auxiliar de Auditoría',
    empresa: 'Auditores del Valle',
    tipo: 'micro-pasantia',
    horasSemanales: 14,
    duracionSemanas: 8,
    duracionLabel: '8 semanas',
    ubicacion: 'San Salvador',
    descripcion: 'Muestreo, papeles de trabajo y revisión de estados financieros.',
    requisitos: JSON.stringify(['Auditoría I', 'Atención al detalle']),
    carreras: JSON.stringify(['Licenciatura en Contaduría Pública']),
  },
  {
    id: 'opp_con_003',
    titulo: 'Proyecto: Automatización contable',
    empresa: 'FinTech Contable SV',
    tipo: 'proyecto',
    horasSemanales: 10,
    duracionSemanas: 5,
    duracionLabel: '5 semanas',
    ubicacion: 'Remoto',
    descripcion: 'Macros y plantillas para agilizar conciliaciones de clientes piloto.',
    requisitos: JSON.stringify(['Excel avanzado', 'Lógica de procesos']),
    carreras: JSON.stringify(['Licenciatura en Contaduría Pública']),
  },
  {
    id: 'opp_con_004',
    titulo: 'Asistente Fiscal',
    empresa: 'Asesoría Tributaria López',
    tipo: 'pasantia',
    horasSemanales: 18,
    duracionSemanas: 12,
    duracionLabel: '12 semanas',
    ubicacion: 'San Salvador',
    descripcion: 'Declaraciones, retenciones y actualización normativa.',
    requisitos: JSON.stringify(['Impuestos', 'Office']),
    carreras: JSON.stringify(['Licenciatura en Contaduría Pública']),
  },
  // Ciencias Jurídicas
  {
    id: 'opp_der_001',
    titulo: 'Asistente Legal Corporativo',
    empresa: 'Bufete Rodríguez & Asoc.',
    tipo: 'pasantia',
    horasSemanales: 18,
    duracionSemanas: 14,
    duracionLabel: '14 semanas',
    ubicacion: 'San Salvador',
    descripcion: 'Revisión de contratos, expedientes y minutas corporativas.',
    requisitos: JSON.stringify(['Derecho civil', 'Redacción jurídica']),
    carreras: JSON.stringify(['Licenciatura en Ciencias Jurídicas']),
  },
  {
    id: 'opp_der_002',
    titulo: 'Proyecto: Clínica jurídica comunitaria',
    empresa: 'ULS — Facultad de Ciencias Jurídicas',
    tipo: 'proyecto',
    horasSemanales: 8,
    duracionSemanas: 6,
    duracionLabel: '6 semanas',
    ubicacion: 'Campus ULS',
    descripcion: 'Asesoría a comunidad en trámites básicos y elaboración de guías.',
    requisitos: JSON.stringify(['Derecho constitucional', 'Ética']),
    carreras: JSON.stringify(['Licenciatura en Ciencias Jurídicas']),
  },
  {
    id: 'opp_der_003',
    titulo: 'Pasante Laboral',
    empresa: 'Ministerio de Trabajo — convenio',
    tipo: 'pasantia',
    horasSemanales: 16,
    duracionSemanas: 10,
    duracionLabel: '10 semanas',
    ubicacion: 'San Salvador',
    descripcion: 'Apoyo en inspecciones y archivo de expedientes laborales.',
    requisitos: JSON.stringify(['Derecho laboral', 'Office']),
    carreras: JSON.stringify(['Licenciatura en Ciencias Jurídicas']),
  },
  {
    id: 'opp_der_004',
    titulo: 'Investigación jurídica',
    empresa: 'Centro de Estudios Legales',
    tipo: 'micro-pasantia',
    horasSemanales: 12,
    duracionSemanas: 8,
    duracionLabel: '8 semanas',
    ubicacion: 'Remoto',
    descripcion: 'Jurisprudencia, fichas bibliográficas y resúmenes para publicaciones.',
    requisitos: JSON.stringify(['Investigación', 'Redacción']),
    carreras: JSON.stringify(['Licenciatura en Ciencias Jurídicas']),
  },
  // Psicología
  {
    id: 'opp_psi_001',
    titulo: 'Asistente en Psicología Clínica',
    empresa: 'Centro de Salud Mental Integral',
    tipo: 'pasantia',
    horasSemanales: 16,
    duracionSemanas: 12,
    duracionLabel: '12 semanas',
    ubicacion: 'San Salvador',
    descripcion: 'Apoyo en evaluación, fichas clínicas y talleres bajo supervisión profesional.',
    requisitos: JSON.stringify(['Psicología clínica', 'Confidencialidad']),
    carreras: JSON.stringify(['Licenciatura en Psicología']),
  },
  {
    id: 'opp_psi_002',
    titulo: 'Psicología Organizacional',
    empresa: 'RH Estratégica SV',
    tipo: 'micro-pasantia',
    horasSemanales: 12,
    duracionSemanas: 8,
    duracionLabel: '8 semanas',
    ubicacion: 'Santa Tecla',
    descripcion: 'Clima laboral, encuestas y propuestas de bienestar en empresa mediana.',
    requisitos: JSON.stringify(['Psicología organizacional', 'Estadística']),
    carreras: JSON.stringify(['Licenciatura en Psicología']),
  },
  {
    id: 'opp_psi_003',
    titulo: 'Proyecto: Programa de tutorías',
    empresa: 'ULS — Bienestar Estudiantil',
    tipo: 'proyecto',
    horasSemanales: 8,
    duracionSemanas: 5,
    duracionLabel: '5 semanas',
    ubicacion: 'Campus ULS',
    descripcion: 'Diseño e implementación de talleres de estudio y manejo del estrés.',
    requisitos: JSON.stringify(['Comunicación', 'Dinámicas grupales']),
    carreras: JSON.stringify(['Licenciatura en Psicología']),
  },
  {
    id: 'opp_psi_004',
    titulo: 'Investigación en neuropsicología',
    empresa: 'Instituto de Investigación ULS',
    tipo: 'proyecto',
    horasSemanales: 10,
    duracionSemanas: 8,
    duracionLabel: '8 semanas',
    ubicacion: 'Campus ULS',
    descripcion: 'Recolección de datos y análisis para estudio piloto con población estudiantil.',
    requisitos: JSON.stringify(['Neuropsicología', 'SPSS o similar']),
    carreras: JSON.stringify(['Licenciatura en Psicología']),
  },
  // Multicarrera / abierto
  {
    id: 'opp_uls_001',
    titulo: 'Proyecto de Investigación UX',
    empresa: 'Lab Innovación ULS',
    tipo: 'proyecto',
    horasSemanales: 8,
    duracionSemanas: 4,
    duracionLabel: '4 semanas',
    ubicacion: 'Campus ULS',
    descripcion: 'Entrevistas con usuarios, prototipos Figma e informe para sistemas universitarios.',
    requisitos: JSON.stringify(['Figma', 'Entrevistas', 'Informes']),
    carreras: JSON.stringify([]),
  },
  {
    id: 'opp_uls_002',
    titulo: 'Voluntariado comunicación institucional',
    empresa: 'Relaciones Públicas ULS',
    tipo: 'micro-pasantia',
    horasSemanales: 6,
    duracionSemanas: 6,
    duracionLabel: '6 semanas',
    ubicacion: 'Campus ULS',
    descripcion: 'Redacción de notas, cobertura de eventos y redes oficiales de la universidad.',
    requisitos: JSON.stringify(['Redacción', 'Redes sociales']),
    carreras: JSON.stringify([]),
  },
];

export async function seedBridge() {
  const existing = await db.select().from(Opportunity).all();
  const existingIds = new Set(existing.map((o) => o.id));

  let added = 0;
  const now = new Date();

  for (const opp of OPORTUNIDADES) {
    if (!existingIds.has(opp.id)) {
      await db.insert(Opportunity).values({
        ...opp,
        activo: true,
        createdAt: now,
      });
      added++;
    }
  }

  if (added > 0) {
    console.log(
      `[seed-bridge] ${added} oportunidades nuevas (${existing.length + added} en total).`
    );
  } else if (existing.length === 0) {
    console.log(`[seed-bridge] ${OPORTUNIDADES.length} oportunidades insertadas.`);
  }
}
